// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC963tFIM27mNWA4s-qD-y-9UqL1AoPfqA',
    appId: '1:122495552906:web:c255f9e43a759eeb850c73',
    messagingSenderId: '122495552906',
    projectId: 'notez-d2c4c',
    authDomain: 'notez-d2c4c.firebaseapp.com',
    storageBucket: 'notez-d2c4c.appspot.com',
    measurementId: 'G-MRGP915MTN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8L090btvLhH6FIZL3p6s83uidWvdEtto',
    appId: '1:122495552906:android:25e743567b15e196850c73',
    messagingSenderId: '122495552906',
    projectId: 'notez-d2c4c',
    storageBucket: 'notez-d2c4c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjirZKoXSJ67l6z4W5c5Bhp2PTbGOOUoM',
    appId: '1:122495552906:ios:9acefff8d8b7784f850c73',
    messagingSenderId: '122495552906',
    projectId: 'notez-d2c4c',
    storageBucket: 'notez-d2c4c.appspot.com',
    iosClientId:
        '122495552906-sugsoi6rqbt0cdo4v38jteh1lqv04l98.apps.googleusercontent.com',
    iosBundleId: 'me.anjace.notez',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjirZKoXSJ67l6z4W5c5Bhp2PTbGOOUoM',
    appId: '1:122495552906:ios:9acefff8d8b7784f850c73',
    messagingSenderId: '122495552906',
    projectId: 'notez-d2c4c',
    storageBucket: 'notez-d2c4c.appspot.com',
    iosClientId:
        '122495552906-sugsoi6rqbt0cdo4v38jteh1lqv04l98.apps.googleusercontent.com',
    iosBundleId: 'me.anjace.notez',
  );
}
